In [1]:
# STEP 1: Library import
import pandas as pd

# STEP 2: Companies file load
# header=1 because first row title untundi (skip cheyyali)
companies = pd.read_excel(
    "D:/Bluestaks/B100 Intelligence/data_raw/companies.xlsx",
    header=1
)

# STEP 3: First rows check
companies.head()

,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
0,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10.0,1657.0,46.0,34.90
1,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10.0,175.0,9.0,8.59
2,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1.0,363.0,11.6,13.64
3,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10.0,67.0,96.5,14.70
4,ADANIPORTS,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Ports & Special Economic Zone Ltd\n,https://in.tradingview.com/chart/?symbol=NSE%3...,Adani Ports & Special Economic Zone is in the ...,http://www.adaniports.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,2.0,265.0,12.9,18.10

In [2]:
# STEP 4: Column names clean
# strip() → spaces remove
# lower() → lowercase
companies.columns = companies.columns.str.strip().str.lower()

# Check columns
companies.columns

Index(['id', 'company_logo', 'company_name', 'chart_link', 'about_company',
       'website', 'nse_profile', 'bse_profile', 'face_value', 'book_value',
       'roce_percentage', 'roe_percentage'],
      dtype='str')

In [3]:
# STEP 5: Duplicate rows remove
companies = companies.drop_duplicates()

# STEP 6: Missing values replace
companies = companies.fillna(0)

# STEP 7: Company name clean (remove \n, spaces)
companies['company_name'] = companies['company_name'].str.strip()

# Structure check
companies.info()

<class 'pandas.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               92 non-null     str
 1   company_logo     92 non-null     object
 2   company_name     92 non-null     str
 3   chart_link       92 non-null     str
 4   about_company    92 non-null     str
 5   website          92 non-null     object
 6   nse_profile      92 non-null     object
 7   bse_profile      92 non-null     object
 8   face_value       92 non-null     float64
 9   book_value       92 non-null     float64
 10  roce_percentage  92 non-null     float64
 11  roe_percentage   92 non-null     float64
dtypes: float64(4), object(4), str(4)
memory usage: 8.8+ KB

In [4]:
# STEP 8: Save clean file
companies.to_csv(
    "D:/Bluestaks/B100 Intelligence/data_clean/companies_clean.csv",
    index=False
)

print("✅ Companies cleaned & saved")

✅ Companies cleaned & saved

In [5]:
# STEP 9: Profit file load
profit = pd.read_excel(
    "D:/Bluestaks/B100 Intelligence/data_raw/profitandloss.xlsx",
    header=1
)

profit.head()

,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
0,61,ABB,Dec 2012,1653,1451,202.0,12.0,33,0,19,215,33.0,145,68.0,25.0
1,62,ABB,Mar 2014,2276,2009,267.0,12.0,49,0,22,295,33.0,198,93.0,25.0
2,63,ABB,Mar 2015,2289,1977,312.0,14.0,48,0,15,344,34.0,229,108.0,29.0
3,64,ABB,Mar 2016,2614,2250,365.0,14.0,50,3,14,398,36.0,255,120.0,29.0
4,65,ABB,Mar 2017,2903,2505,398.0,14.0,57,2,16,436,37.0,277,130.0,31.0

In [6]:
# STEP 10: Profit columns clean
profit.columns = profit.columns.str.strip().str.lower()
profit.columns

Index(['id', 'company_id', 'year', 'sales', 'expenses', 'operating_profit',
       'opm_percentage', 'other_income', 'interest', 'depreciation',
       'profit_before_tax', 'tax_percentage', 'net_profit', 'eps',
       'dividend_payout'],
      dtype='str')

In [7]:
# STEP 11: Clean profit data
profit = profit.drop_duplicates()
profit = profit.fillna(0)

profit.info()

<class 'pandas.DataFrame'>
RangeIndex: 1276 entries, 0 to 1275
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1276 non-null   int64
 1   company_id         1276 non-null   str
 2   year               1276 non-null   str
 3   sales              1276 non-null   int64
 4   expenses           1276 non-null   int64
 5   operating_profit   1276 non-null   float64
 6   opm_percentage     1276 non-null   float64
 7   other_income       1276 non-null   int64
 8   interest           1276 non-null   int64
 9   depreciation       1276 non-null   int64
 10  profit_before_tax  1276 non-null   int64
 11  tax_percentage     1276 non-null   float64
 12  net_profit         1276 non-null   int64
 13  eps                1276 non-null   float64
 14  dividend_payout    1276 non-null   float64
dtypes: float64(5), int64(8), str(2)
memory usage: 149.7 KB

In [8]:
# STEP 12: Save clean profit
profit.to_csv(
    "D:/Bluestaks/B100 Intelligence/data_clean/profit_clean.csv",
    index=False
)

print("✅ Profit cleaned & saved")

✅ Profit cleaned & saved

In [9]:
# STEP: Balance sheet load
balance = pd.read_excel(
    "D:/Bluestaks/B100 Intelligence/data_raw/balancesheet.xlsx",
    header=1
)

# Check data
balance.head()

,id,company_id,year,equity_capital,reserves,borrowings,other_liabilities,total_liabilities,fixed_assets,cwip,investments,other_asset,total_assets
0,136,ABB,Dec 2012,21.0,626,0,260,907,109,1,0,798,907
1,137,ABB,Mar 2014,21.0,767,0,351,1139,98,1,0,1040,1139
2,138,ABB,Mar 2015,21.0,916,0,436,1374,96,4,0,1274,1374
3,139,ABB,Mar 2016,21.0,1174,0,421,1616,108,3,0,1505,1616
4,140,ABB,Mar 2017,21.0,1366,0,679,2066,110,6,0,1950,2066

In [10]:
# STEP: Column names clean
balance.columns = balance.columns.str.strip().str.lower()

# Check columns
balance.columns

Index(['id', 'company_id', 'year', 'equity_capital', 'reserves', 'borrowings',
       'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip',
       'investments', 'other_asset', 'total_assets'],
      dtype='str')

In [11]:
# STEP: Cleaning
balance = balance.drop_duplicates()
balance = balance.fillna(0)

balance.info()

<class 'pandas.DataFrame'>
RangeIndex: 1312 entries, 0 to 1311
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1312 non-null   int64
 1   company_id         1312 non-null   str
 2   year               1312 non-null   str
 3   equity_capital     1312 non-null   float64
 4   reserves           1312 non-null   int64
 5   borrowings         1312 non-null   int64
 6   other_liabilities  1312 non-null   int64
 7   total_liabilities  1312 non-null   int64
 8   fixed_assets       1312 non-null   int64
 9   cwip               1312 non-null   int64
 10  investments        1312 non-null   int64
 11  other_asset        1312 non-null   int64
 12  total_assets       1312 non-null   int64
dtypes: float64(1), int64(10), str(2)
memory usage: 133.4 KB

In [12]:
# STEP: Save clean file
balance.to_csv(
    "D:/Bluestaks/B100 Intelligence/data_clean/balance_clean.csv",
    index=False
)

print("✅ Balance cleaned")

✅ Balance cleaned

In [13]:
# STEP: Cashflow load
cashflow = pd.read_excel(
    "D:/Bluestaks/B100 Intelligence/data_raw/cashflow.xlsx",
    header=1
)

# Check data
cashflow.head()

,id,company_id,year,operating_activity,investing_activity,financing_activity,net_cash_flow
0,37,TCS,Mar-13,11615.0,-6038.0,-5729.0,-152.0
1,38,TCS,Mar-14,14751.0,-9452.0,-5673.0,-374.0
2,39,TCS,Mar-15,19369.0,-1807.0,-17168.0,394.0
3,40,TCS,Mar-16,19109.0,-5010.0,-9666.0,4433.0
4,41,TCS,Mar-17,25223.0,-16895.0,-11026.0,-2698.0

In [14]:
# Clean column names
cashflow.columns = cashflow.columns.str.strip().str.lower()

cashflow.columns

Index(['id', 'company_id', 'year', 'operating_activity', 'investing_activity',
       'financing_activity', 'net_cash_flow'],
      dtype='str')

In [15]:
# Remove duplicates
cashflow = cashflow.drop_duplicates()

# Fill missing values
cashflow = cashflow.fillna(0)

cashflow.info()

<class 'pandas.DataFrame'>
RangeIndex: 1187 entries, 0 to 1186
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  1187 non-null   int64
 1   company_id          1187 non-null   str
 2   year                1187 non-null   str
 3   operating_activity  1187 non-null   float64
 4   investing_activity  1187 non-null   float64
 5   financing_activity  1187 non-null   float64
 6   net_cash_flow       1187 non-null   float64
dtypes: float64(4), int64(1), str(2)
memory usage: 65.0 KB

In [16]:
# Save clean file
cashflow.to_csv(
    "D:/Bluestaks/B100 Intelligence/data_clean/cashflow_clean.csv",
    index=False
)

print("✅ Cashflow cleaned")

✅ Cashflow cleaned

In [17]:
analysis = pd.read_excel(
    "D:/Bluestaks/B100 Intelligence/data_raw/analysis.xlsx",
    header=1
)

analysis.columns = analysis.columns.str.strip().str.lower()
analysis = analysis.drop_duplicates()
analysis = analysis.fillna(0)

analysis.to_csv(
    "D:/Bluestaks/B100 Intelligence/data_clean/analysis_clean.csv",
    index=False
)

print("✅ Analysis cleaned")

✅ Analysis cleaned

In [18]:
pros = pd.read_excel(
    "D:/Bluestaks/B100 Intelligence/data_raw/prosandcons.xlsx",
    header=1
)

pros.columns = pros.columns.str.strip().str.lower()
pros = pros.drop_duplicates()
pros = pros.fillna("")

pros.to_csv(
    "D:/Bluestaks/B100 Intelligence/data_clean/pros_clean.csv",
    index=False
)

print("✅ Pros & Cons cleaned")

✅ Pros & Cons cleaned

In [20]:
import pandas as pd
import os

os.makedirs("D:/Bluestaks/B100 Intelligence/data_clean", exist_ok=True)

# Load files
companies = pd.read_csv("D:/Bluestaks/B100 Intelligence/data_clean/companies_clean.csv")
profit = pd.read_csv("D:/Bluestaks/B100 Intelligence/data_clean/profit_clean.csv")
balance = pd.read_csv("D:/Bluestaks/B100 Intelligence/data_clean/balance_clean.csv")
cashflow = pd.read_csv("D:/Bluestaks/B100 Intelligence/data_clean/cashflow_clean.csv")

# 🔥 IMPORTANT FIX
companies['id'] = companies['id'].astype(str)
profit['id'] = profit['id'].astype(str)
balance['id'] = balance['id'].astype(str)
cashflow['id'] = cashflow['id'].astype(str)

# Merge
df1 = pd.merge(companies, profit, on="id", how="inner")
df2 = pd.merge(df1, balance, on="id", how="inner")
final_df = pd.merge(df2, cashflow, on="id", how="inner")

# Save
final_df.to_csv(
    "D:/Bluestaks/B100 Intelligence/data_clean/final_dataset.csv",
    index=False
)

print("🔥 FINAL DATASET CREATED SUCCESSFULLY")

🔥 FINAL DATASET CREATED SUCCESSFULLY

In [21]:
os.listdir("D:/Bluestaks/B100 Intelligence/data_clean")

['analysis_clean.csv',
 'balance_clean.csv',
 'cashflow_clean.csv',
 'companies_clean.csv',
 'final_dataset.csv',
 'profit_clean.csv',
 'pros_clean.csv']