In [3]:
import pandas as pd

# Load cleaned files
companies = pd.read_csv("D:/Bluestaks/B100 Intelligence/data_clean/companies_clean.csv")
profit = pd.read_csv("D:/Bluestaks/B100 Intelligence/data_clean/profit_clean.csv")
balance = pd.read_csv("D:/Bluestaks/B100 Intelligence/data_clean/balance_clean.csv")
cashflow = pd.read_csv("D:/Bluestaks/B100 Intelligence/data_clean/cashflow_clean.csv")

print("✅ Data loaded")

✅ Data loaded

In [4]:
print(companies['id'].head())
print(profit.head())

0           ABB
1    ADANIENSOL
2      ADANIENT
3    ADANIGREEN
4    ADANIPORTS
Name: id, dtype: str
   id company_id      year  sales  expenses  operating_profit  opm_percentage  \
0  61        ABB  Dec 2012   1653      1451             202.0            12.0
1  62        ABB  Mar 2014   2276      2009             267.0            12.0
2  63        ABB  Mar 2015   2289      1977             312.0            14.0
3  64        ABB  Mar 2016   2614      2250             365.0            14.0
4  65        ABB  Mar 2017   2903      2505             398.0            14.0

   other_income  interest  depreciation  profit_before_tax  tax_percentage  \
0            33         0            19                215            33.0
1            49         0            22                295            33.0
2            48         0            15                344            34.0
3            50         3            14                398            36.0
4            57         2            16                436            37.0

   net_profit    eps  dividend_payout
0         145   68.0             25.0
1         198   93.0             25.0
2         229  108.0             29.0
3         255  120.0             29.0
4         277  130.0             31.0

In [6]:
# companies lo id ni company_id ga rename chestham
companies.rename(columns={"id": "company_id"}, inplace=True)

In [7]:
companies['company_id'] = companies['company_id'].astype(str).str.strip()
profit['company_id'] = profit['company_id'].astype(str).str.strip()
balance['company_id'] = balance['company_id'].astype(str).str.strip()
cashflow['company_id'] = cashflow['company_id'].astype(str).str.strip()

In [8]:
df1 = pd.merge(companies, profit, on="company_id", how="inner")
df2 = pd.merge(df1, balance, on="company_id", how="inner")
final_df = pd.merge(df2, cashflow, on="company_id", how="inner")

print(final_df.shape)

(192837, 44)

In [9]:
final_df.to_csv(
    "D:/Bluestaks/B100 Intelligence/data_clean/final_dataset.csv",
    index=False
)

print("🔥 FINAL DATASET READY")

🔥 FINAL DATASET READY

In [10]:
# STEP 1: Final dataset load
import pandas as pd

df = pd.read_csv("D:/Bluestaks/B100 Intelligence/data_clean/final_dataset.csv")

df.head()

,company_id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,...,cwip,investments,other_asset,total_assets,id,year,operating_activity,investing_activity,financing_activity,net_cash_flow
0,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10.0,1657.0,...,1,0,798,907,61,Dec 2012,101.0,-59.0,-42.0,1.0
1,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10.0,1657.0,...,1,0,798,907,62,Mar 2014,155.0,-144.0,-42.0,-31.0
2,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10.0,1657.0,...,1,0,798,907,63,Mar 2015,215.0,-187.0,-58.0,-30.0
3,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10.0,1657.0,...,1,0,798,907,64,Mar 2016,249.0,-77.0,-80.0,91.0
4,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10.0,1657.0,...,1,0,798,907,65,Mar 2017,307.0,-155.0,-90.0,62.0

In [11]:
# STEP 2: Check useful columns
df.columns

Index(['company_id', 'company_logo', 'company_name', 'chart_link',
       'about_company', 'website', 'nse_profile', 'bse_profile', 'face_value',
       'book_value', 'roce_percentage', 'roe_percentage', 'id_x', 'year_x',
       'sales', 'expenses', 'operating_profit', 'opm_percentage',
       'other_income', 'interest', 'depreciation', 'profit_before_tax',
       'tax_percentage', 'net_profit', 'eps', 'dividend_payout', 'id_y',
       'year_y', 'equity_capital', 'reserves', 'borrowings',
       'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip',
       'investments', 'other_asset', 'total_assets', 'id', 'year',
       'operating_activity', 'investing_activity', 'financing_activity',
       'net_cash_flow'],
      dtype='str')

In [14]:
# Remove duplicate id and year columns
df = df.drop(columns=['id_x', 'id_y', 'id', 'year_x', 'year_y'])

df.columns

Index(['company_id', 'company_logo', 'company_name', 'chart_link',
       'about_company', 'website', 'nse_profile', 'bse_profile', 'face_value',
       'book_value', 'roce_percentage', 'roe_percentage', 'sales', 'expenses',
       'operating_profit', 'opm_percentage', 'other_income', 'interest',
       'depreciation', 'profit_before_tax', 'tax_percentage', 'net_profit',
       'eps', 'dividend_payout', 'equity_capital', 'reserves', 'borrowings',
       'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip',
       'investments', 'other_asset', 'total_assets', 'year',
       'operating_activity', 'investing_activity', 'financing_activity',
       'net_cash_flow', 'ml_score', 'category'],
      dtype='str')

In [15]:
df[['company_id', 'roe_percentage', 'roce_percentage', 'net_profit']].head()

  company_id  roe_percentage  roce_percentage  net_profit
0        ABB            34.9             46.0         145
1        ABB            34.9             46.0         145
2        ABB            34.9             46.0         145
3        ABB            34.9             46.0         145
4        ABB            34.9             46.0         145

In [16]:
# Group by company and take average

df_grouped = df.groupby('company_id').agg({
    'roe_percentage': 'mean',
    'roce_percentage': 'mean',
    'net_profit': 'mean'
}).reset_index()

df_grouped.head()

   company_id  roe_percentage  roce_percentage   net_profit
0         ABB           34.90             46.0   574.846154
1  ADANIENSOL            8.59              9.0   731.416667
2    ADANIENT           13.64             11.6  1838.769231
3  ADANIGREEN           14.70             96.5   456.000000
4  ADANIPORTS           18.10             12.9  4401.692308

In [17]:
df_grouped['ml_score'] = (
    df_grouped['roe_percentage'] * 0.4 +
    df_grouped['roce_percentage'] * 0.3 +
    (df_grouped['net_profit'] / 1000) * 0.3
)

In [18]:
def classify(score):
    if score > 50:
        return "Strong"
    elif score > 25:
        return "Average"
    else:
        return "Weak"

df_grouped['category'] = df_grouped['ml_score'].apply(classify)

In [19]:
df_grouped.to_csv(
    "D:/Bluestaks/B100 Intelligence/data_clean/final_ml_dataset.csv",
    index=False
)

print("🔥 FINAL CLEAN ML DATASET READY")

🔥 FINAL CLEAN ML DATASET READY